spring.application.name=userdemo-1
spring.datasource.url=jdbc:mysql://localhost:3306/hibernatedb
spring.datasource.driverClassName= com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081